USE [master]
GO

CREATE DATABASE [Neighbors]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Neighbors', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Neighbors.mdf' , SIZE = 90752KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Neighbors_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Neighbors_log.ldf' , SIZE = 122880KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO